(()=>{
if(typeof D!=='undefined'&&D[0]&&Array.isArray(D[0][2])){
D[0][0]='DAY 1 · KIX 입국 → 호텔 → 도톤보리';D[0][1]='9/17 THU · 첫날 초행길 상세';D[0][2]=[
['13:00','k','부산 출발 · TW0321','PUS 13:00 → KIX 14:30 예정. 위탁수하물 15kg/인.','transit'],
['14:30*','k','KIX 제1터미널 도착','착륙 후 국제선 도착 동선을 따라 이동. 게이트 위치에 따라 입국심사장까지 10~20분 정도 걸릴 수 있음.','walking'],
['14:45*','k','Visit Japan Web · 입국심사','Visit Japan Web QR과 여권 준비. 통합 키오스크가 보이면 QR+여권 스캔 → 안내된 외국인 입국심사 동선으로 이동. 현장 지문·얼굴 확인 안내에 따르기.','walking'],
['15:10*','k','위탁수하물 찾기','입국심사 후 Baggage Claim으로 이동. 전광판에서 TW0321 수하물 벨트를 확인하고 캐리어 수령.','walking'],
['15:30*','k','세관 통과','짐을 가지고 Customs / 세관으로 이동. Visit Japan Web 등록자는 전자신고 안내 동선을 이용하고 현장 지시에 따라 통과.','walking'],
['15:40*','k','도착 로비 1F → 전철역 2F','세관을 나오면 T1 국제선 도착 로비 1층. 엘리베이터·에스컬레이터로 2층 → “Railways / Train / 鉄道” 표지판 → 연결통로를 건너 간사이공항역으로 이동.','walking'],
['15:50*','k','여자친구 실물 ICOCA 구매','간사이공항역 JR 또는 난카이에서 ICOCA 1장 구입. 너는 iPhone ICOCA 사용. 구입·충전용 엔화 현금을 준비.','walking'],
['16:05*','k','난카이(NANKAI) 개찰구로','JR이 아니라 “NANKAI / 南海” 표지판을 찾기. 두 사람 각각 ICOCA를 찍고 입장. “Airport Express / 空港急行 · Namba 난바 방면” 탑승.','transit'],
['16:15*','k','난카이 공항급행 → 덴가차야','Kansai-Airport → Tengachaya(天下茶屋). 라피트가 아닌 일반 공항급행이면 별도 특급권 불필요. 실제 출발 시각은 역 전광판/Google Maps 확인.','transit'],
['16:55*','h','덴가차야에서 Osaka Metro 환승','Tengachaya 하차 → 난카이 개찰구 밖 → “Osaka Metro 堺筋線 / Sakaisuji Line / K” 표지판. K20에서 북쪽 방면(Tenroku·Kita-Senri·Takatsuki·Kyoto 방향) 탑승.','transit'],
['17:10*','h','닛폰바시 K17 하차','K20 덴가차야 → K19 도부츠엔마에 → K18 에비스초 → K17 닛폰바시. 3정거장. 일본어 역명은 日本橋.','transit'],
['17:20*','h','6번 출구 → 호텔 체크인','닛폰바시역 동쪽 개찰구 → 6번 출구. 지상에 나오면 오른쪽으로 U턴 → 약 50m 직진 → 오른쪽 Sotetsu Grand Fresa Osaka Namba.','walking'],
['18:00*','d','도톤보리 · 글리코사인','짐 정리 후 도보 이동. 입국·수하물이 늦어지면 이후 일정은 그대로 뒤로 밀지 말고 유연하게 줄이기.','walking'],
['18:30*','d','첫 저녁 · 맛집 후보에서 선택','오코노미야키·쿠시카츠·우동 등 맛집 탭 후보 중 현장 대기시간을 보고 결정.','walking'],
['20:00*','s','신사이바시 산책 · 쇼핑','체력이 남으면 쇼핑·드럭스토어. 늦어졌다면 생략하고 숙소 복귀.','walking']];
const dayEl=document.querySelector('.day[data-day="0"]');if(dayEl){dayEl.innerHTML=`<div class="dh"><h3>${D[0][0]}</h3><span>${D[0][1]}</span></div>`;D[0][2].forEach(a=>{const p=P[a[1]],e=document.createElement('article');e.className='stop';e.dataset.day=0;e.innerHTML=`<div class="time">${a[0]}</div><div><strong>${a[2]}</strong><p>${a[3]}</p><div class="act"><a class="loc" target="_blank" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p[2])}&hl=ko">📍 위치</a><a class="go" target="_blank" href="https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(p[2])}&travelmode=${a[4]}&hl=ko">🚇 길찾기</a></div></div>`;e.addEventListener('click',z=>{if(z.target.closest('a'))return;document.querySelectorAll('.stop,.marker,.opt').forEach(x=>x.classList.remove('on'));e.classList.add('on');if(typeof map!=='undefined'&&typeof M!=='undefined'){const k=a[1],pt=P[k];if(!map.hasLayer(M[k]))M[k].addTo(map);document.getElementById('p'+k)?.classList.add('on');map.flyTo([pt[3],pt[4]],k==='k'?10.5:14,{duration:.4});M[k].openPopup()}});dayEl.appendChild(e)})}}
}
})();
(()=>{const root=document.getElementById('prepChecklist');if(!root)return;const groups=[['지금 확인',['USJ 입장권 QR 2명분 정리','Express Pass QR 2명분 정리','익스프레스 지정시간 캡처/메모','USJ 앱 티켓 등록 확인','DAY 3 계획안 여자친구와 상의']],['입국·통신',['여권 유효기간 확인',{t:'Visit Japan Web 등록',links:[['공식 안내','https://services.digital.go.jp/visit-japan-web/']]},'항공권 예약내역 캡처','호텔 예약내역 캡처','eSIM 또는 로밍 결정·설치']],['교통·결제',[{t:'ICOCA 준비 · 나는 iPhone / 여자친구는 KIX에서 실물 구매',links:[['JR서일본 ICOCA','https://www.westjr.co.jp/global/kr/howto/icoca/applepay/'],['KIX 실물 ICOCA 구매','https://www.kansai-airport.or.jp/kr/faq/1121']]},'KIX → 호텔: 난카이 공항급행 → 덴가차야 → 사카이스지선 → 닛폰바시 K17','호텔 → USJ 출발시간 확인','귀국일 호텔 → KIX 이동시간 확정','해외결제 카드 사용 가능 여부 확인','엔화 현금 소액 준비']],['일정·예약',['도톤보리 리버크루즈 탈지 결정','우메다 스카이빌딩 일정 확정','오사카 주유패스 최종 판단','첫날·DAY3·USJ 식사 후보 선정','필요한 인기 맛집 예약 여부 확인']],['출발 1주 전',['오사카 날씨·태풍 가능성 확인','USJ 운영시간 재확인','익스프레스 지정시간 재확인','항공 터미널 확인','공항철도 시간표 확인','여행자보험 가입']],['출발 전날',['여권·지갑·카드·현금 확인','USJ QR·항공권·호텔 예약서 저장','Visit Japan Web QR 저장','보조배터리·충전기 준비','우산·얇은 겉옷·상비약 준비','위탁수하물 15kg 초과 여부 확인']]];const key='osakaPrepV33';let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}')}catch{}root.innerHTML='<div class="prep-progress"><div class="bar"><div class="fill" id="prepFill"></div></div><strong id="prepCount">0 / 0 완료</strong></div><div class="prep-board" id="prepBoard"></div><div class="prep-note">체크 상태는 이 기기 브라우저에 저장돼요. 공식 링크는 새 창에서 열립니다.</div>';const board=document.getElementById('prepBoard');let total=0;groups.forEach((g,gi)=>{const box=document.createElement('section');box.className='prep-group';box.innerHTML=`<h3>${g[0]}</h3><div class="prep-items"></div>`;const items=box.querySelector('.prep-items');g[1].forEach((item,ii)=>{total++;const id=`g${gi}i${ii}`,obj=typeof item==='string'?{t:item}:item;const row=document.createElement('div');row.className='prep-item';row.innerHTML=`<input id="prep-${id}" type="checkbox" data-id="${id}"><div class="prep-item-body"><label for="prep-${id}"><span>${obj.t}</span></label>${obj.links?`<div class="prep-links">${obj.links.map(x=>`<a target="_blank" rel="noopener" href="${x[1]}">↗ ${x[0]}</a>`).join('')}</div>`:''}</div>`;const cb=row.querySelector('input');cb.checked=!!saved[id];row.classList.toggle('done',cb.checked);cb.addEventListener('change',()=>{saved[id]=cb.checked;localStorage.setItem(key,JSON.stringify(saved));row.classList.toggle('done',cb.checked);update()});items.appendChild(row)});board.appendChild(box)});function update(){const checked=[...root.querySelectorAll('input[type=checkbox]')].filter(x=>x.checked).length;document.getElementById('prepCount').textContent=`${checked} / ${total} 완료`;document.getElementById('prepFill').style.width=`${total?checked/total*100:0}%`}update()})();
import('./food-v34.js?v=34');